import { getAuthContext } from '@/lib/auth-context'
import { NextResponse } from 'next/server'

export async function POST(request: Request) {
  try {
    const auth = await getAuthContext()
    if (!auth) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    const { user, supabase } = auth

    const { proof_ids } = await request.json()

    if (!Array.isArray(proof_ids) || proof_ids.length < 2) {
      return NextResponse.json(
        { error: 'At least 2 proof IDs are required' },
        { status: 400 }
      )
    }

    // Fetch all proofs to combine
    const { data: proofsToMerge, error: fetchError } = await supabase
      .from('proofs')
      .select('*')
      .in('id', proof_ids)
      .eq('user_id', user.id)

    if (fetchError || !proofsToMerge || proofsToMerge.length === 0) {
      return NextResponse.json(
        { error: 'Failed to fetch proofs' },
        { status: 500 }
      )
    }

    // For each selected proof, fetch ONLY its version group (not all proofs with same name)
    let allVersionsToMerge: any[] = []

    for (const proof of proofsToMerge) {
      let versions: any[] = []

      if (proof.proof_group_id) {
        // Proof is part of a group - fetch all proofs in that group
        const { data } = await supabase
          .from('proofs')
          .select('*')
          .eq('proof_group_id', proof.proof_group_id)
          .eq('user_id', user.id)
        versions = data || []
      } else if (proof.parent_proof_id) {
        // Proof has parent but no group - fetch by proof_name (legacy grouping)
        const proofName = proof.proof_name || proof.file_name
        const { data } = await supabase
          .from('proofs')
          .select('*')
          .eq('proof_name', proofName)
          .eq('user_id', user.id)
        versions = data || []
      } else {
        // Standalone proof - only include this single proof
        versions = [proof]
      }

      if (versions.length > 0) {
        allVersionsToMerge = [...allVersionsToMerge, ...versions]
      }
    }

    // Remove duplicates by ID
    const uniqueVersions = Array.from(
      new Map(allVersionsToMerge.map(v => [v.id, v])).values()
    )

    // Sort all versions by created_at timestamp (earliest first)
    uniqueVersions.sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime())

    // Generate a new proof_group_id for all versions
    const groupId = crypto.randomUUID()

    // Helper: Detect auto-generated file count names (e.g., "44 files", "1 file")
    const isAutoGeneratedName = (name: string) => {
      return /^\d+\s+files?$/.test(name.trim())
    }

    // Pick the best proof name: prioritize user-given names over auto-generated ones
    // If multiple user-given names exist, use the most recent one
    const userGivenProofs = uniqueVersions
      .filter(p => {
        const name = p.proof_name || p.file_name
        return !isAutoGeneratedName(name)
      })
      .reverse() // Reverse to get most recent first (since array is sorted earliest first)

    const unifiedProofName = userGivenProofs.length > 0
      ? (userGivenProofs[0].proof_name || userGivenProofs[0].file_name)
      : (uniqueVersions[0].proof_name || uniqueVersions[0].file_name)

    // Get description fields from the most recent version that has them
    const versionWithDescription = [...uniqueVersions]
      .reverse()
      .find(v => v.description_title || v.description_body)
    const unifiedDescriptionTitle = versionWithDescription?.description_title || null
    const unifiedDescriptionBody = versionWithDescription?.description_body || null

    // Update all proofs with:
    // - Same proof_group_id
    // - Same proof_name
    // - Same description fields
    // - Re-numbered version_number (1, 2, 3...)
    const updates = uniqueVersions.map((proof, index) => ({
      id: proof.id,
      proof_group_id: groupId,
      proof_name: unifiedProofName,
      description_title: unifiedDescriptionTitle,
      description_body: unifiedDescriptionBody,
      version_number: index + 1,
      parent_proof_id: index === 0 ? null : uniqueVersions[index - 1].id,
    }))

    // Execute updates
    for (const update of updates) {
      const { data: updatedProof, error: updateError } = await supabase
        .from('proofs')
        .update({
          proof_group_id: update.proof_group_id,
          proof_name: update.proof_name,
          description_title: update.description_title,
          description_body: update.description_body,
          version_number: update.version_number,
          parent_proof_id: update.parent_proof_id,
        })
        .eq('id', update.id)
        .select()
        .single()

      if (updateError) {
        console.error('Error updating proof:', updateError)
        return NextResponse.json(
          { error: 'Failed to update proofs' },
          { status: 500 }
        )
      }

    }

    return NextResponse.json({
      success: true,
      message: `Combined ${uniqueVersions.length} versions`,
      proof_group_id: groupId,
      unified_proof_name: unifiedProofName,
    })
  } catch (error: any) {
    console.error('Error combining proofs:', error)
    return NextResponse.json(
      { error: error.message || 'Internal server error' },
      { status: 500 }
    )
  }
}
